### ISSUE TITLE
Errors within the isolate

### ISSUE THREAD

**Issue by virtualzeta** [Maksimka101/combine#19]
I'm testing the `combine` plugin now hoping to fix issues encountered with other approaches but I'm running into new problems.

I was happy to note, for example, that from within the block:
- I can use `rootBundle`;
- I can transfer data that is not necessarily primitive.

But I am unhappy to note that I am getting error in below situations creating the isolate using `Combine().spawn`.

With `pathImage` as `String`.

```
var fileImage = await rootBundle.load(pathImage);
var byteImage = fileImage.buffer.asUint8List();
ImmutableBuffer bufferImage=
   await ui.ImmutableBuffer.fromUint8List(byteImage);
var imageDetails = await ui.ImageDescriptor.encoded(bufferImage);
```

`Exception: Failed to access the internal image decoder registry on this isolate. Please file a bug on https://github.com/flutter/flutter/issues.`

Or with `imageElement` as `Image`.

```
Completer<ui.Image> imageReference = Completer<ui.Image>();
imageElement.image
 .resolve(const ImageConfiguration())
 .addListener(ImageStreamListener(
	 (ImageInfo imageElement, bool _) {
imageReference.complete(imageElement.image);
}));
ui.Image? imageDetails = await imageReference.future;
```

`_debugInitializedType == null': is not true.`

Error I also get when I call `WidgetsFlutterBinding.ensureInitialized()` and who knows how many other things.

The same code works normally off the isolate.

How can these problems be solved?

These are just the first errors that have occurred to me for image management but I suspect that there may be many others in using the plugin given the premises.

**Comment by Maksimka101** [comment]
Hello

Unfortunately, it's not possible to use the `dart:ui` package in the non-main isolate. There is an [issue](https://github.com/flutter/flutter/issues/10647) that is opened for a 5 years so far

You can try to use the [`flutter_isolate`](https://pub.dev/packages/flutter_isolate) package. It creates a flutter engine instance, so probably you will be able to use the `dart:ui` package. However, people in the issue above [mention](https://github.com/flutter/flutter/issues/10647#issuecomment-1244859297), that they face another issues with the `flutter_isolate`

**Comment by virtualzeta** [comment]
Yes, I'm aware of it.
As of yesterday I was just testing with flutter_isolate and was referring to those problems.

**Comment by Maksimka101** [comment]
Unfortunately, there is nothing this plugin can do. I can only suggest you to use some native library with ffi bindings for image processing
