### ISSUE TITLE
[Question] Do we need to cancel a StreamSubscription ?

### ISSUE THREAD

**Issue by Mihai-B** [Maksimka101/combine#20]
I am still in the testing fase of this plugin but I am starting to like it. Thank you for your work.
I do have a question related to the functionality of this plugin:

I want to now if I have to manualy close a StreamSubscription or not.
So if you have a code that looks like this:
```
CombineInfo isolateInfo = await Combine().spawn((context) {
  print("Argument from main isolate: ${context.argument}");

  context.messenger.messages.listen((message) {
    print("Message from main isolate: $message");
    context.messenger.send("Hello from isolate!");
  });
}, argument: 42);

 StreamSubscription<Object?> workerSubscription = isolateInfo.messenger.messages.listen((message) {
     // your code to handle messages from isolate
    });
```

Is it required to close the StreamSubscription or when calling the method ` isolateInfo.isolate.kill();` will also handle the closing of the StreamSubscriptions ?

**Comment by Maksimka101** [comment]
Hello. Glad to hear it

All combine related stuff, streams included, will be closed when it's killed. So your subscription will be closed as well

**Comment by Mihai-B** [comment]
Nice, thank you for the info.
