### ISSUE TITLE
Cannot load Firebase inside isoalte

### ISSUE THREAD

**Issue by Mihai-B** [Maksimka101/combine#21]
I am not sure actually if this is a combine plugin related.
Combine works fine until I add the steps to start FirebaseAuth and Firebasestore.

The error I get is:
```
W/ProviderInstaller( 4962): Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
F/libc    ( 4962): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4962 (.cookingjournal), pid 4962 (.cookingjournal)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone64_x86_64/emu64xa:14/UPB5.230623.003/10615560:user/release-keys'
Revision: '0'
ABI: 'x86_64'
Timestamp: 2023-08-27 23:03:33.909536880+0300
Process uptime: 29s
```

The code that configures firebase is
```
final firebaseApp = await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    final FirebaseAuth auth = FirebaseAuth.instanceFor(app: firebaseApp);
    final fireStoreRepo = FirebaseFirestore.instanceFor(app: firebaseApp);
    fireStoreRepo.disableNetwork();
```

Note: code works when in main isolate.

Can this be related to Combine or maybe there is another problem ?

**Comment by Maksimka101** [comment]
Hello. Can you please send a repo with minimum reproducible code? 

I've tested firebase initialization and it works fine. \
Also, I've tried to google this exception and everybody suggests to add network permissions on android. However, as you say, it works in main isolate. So, looks like problem isn't in permissions

**Comment by Mihai-B** [comment]
I am not sure exactly what changed, but now it looks like it is working. I did not test with google cloud functions and firebase auth, only with crashlitics this time.
I think we can close this one.

Also: The idea of this package is very neat. Thank you for the hard work
